"""Initial Migracion

Revision ID: d4c332a1635c
Revises: 
Create Date: 2025-09-23 22:07:48.321602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4c332a1635c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsavel',
    sa.Column('id_responsavel', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_completo', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('especialidade', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_responsavel')
    )
    op.create_table('solicitante',
    sa.Column('id_solicitante', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_completo', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('rua', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_solicitante')
    )
    op.create_table('chamado',
    sa.Column('id_chamado', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('id_solicitanteFk', sa.Integer(), nullable=True),
    sa.Column('id_responsavelFk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_responsavelFk'], ['responsavel.id_responsavel'], ),
    sa.ForeignKeyConstraint(['id_solicitanteFk'], ['solicitante.id_solicitante'], ),
    sa.PrimaryKeyConstraint('id_chamado')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chamado')
    op.drop_table('solicitante')
    op.drop_table('responsavel')
    # ### end Alembic commands ###
